apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lbaas-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: lbaas-operator
    spec:
      containers:
      - name: lbaas-operator
        image: lbaas
        command:
        - lbaas-operator
        # Uncomment to act for resources in all namespaces. More information in doc/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

